# Generated by Django 3.2 on 2021-05-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=50)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=20)),
                ('satici', models.CharField(max_length=50)),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
