# Generated by Django 3.2 on 2021-05-03 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('sehir', models.CharField(max_length=50)),
                ('sektor', models.CharField(max_length=50)),
                ('katilma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='urun',
            name='satici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.satici'),
        ),
    ]
