# Generated by Django 3.2 on 2021-05-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0002_auto_20210504_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='satici',
        ),
        migrations.DeleteModel(
            name='Satici',
        ),
    ]
