# Generated by Django 3.2 on 2021-05-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0003_auto_20210504_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('sehir', models.CharField(max_length=50)),
                ('sektor', models.CharField(max_length=50)),
                ('katilma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
